#!/bin/sh                                                                                   

dump_sql=`mktemp`
echo $dump_sql

./pull.pl > $dump_sql
scp $dump_sql lilibio@ftp.lilibio.com:/homez.387/lilibio/www/script/Sync-DB/temp/
dump_sql=`basename $dump_sql`
ssh lilibio@ftp.lilibio.com "cd www/script/Sync-DB/ && ./push.pl temp/$dump_sql"
ssh lilibio@ftp.lilibio.com "rm www/script/Sync-DB/temp/*"


